services:
  web:
    container_name: cdi_ielts-web
    build: .
    volumes:
      - .:/app
    ports:
      - "${PORT:-8700}:${PORT:-8700}"
    depends_on:
      db:
        condition: service_started
    env_file:
      - .env
    restart: on-failure
    networks:
      - cdi_network
    environment:
      - PORT=${PORT:-8700}

  db:
    container_name: cdi_ielts-db
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - cdi_network

  bot:
    container_name: cdi_ielts-bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BOT_PORT=${BOT_PORT:-8081}
    ports:
      - "${BOT_PORT:-8081}:${BOT_PORT:-8081}"
    depends_on:
      web:
        condition: service_started
    networks:
      - cdi_network

volumes:
  postgres_data:

networks:
  cdi_network:
    driver: bridge